# ==========================================
# 1. Configuração do Servidor (Porta)
# ==========================================
server.port=8081

# ==========================================
# 2. Configuração do Banco de Dados (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=281220

# Cria e atualiza as tabelas automaticamente no banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# 3. Chave Secreta do Token JWT
# ==========================================
jwt.secret=UmaChaveMuitoSeguraEGrandeParaOAlgoritmoHS256_DiogoAuthApi_2024

# ==========================================
# 4. Configuração do Sistema de E-mail (Local/Simulado)
# ==========================================
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test